language: node_js
node_js:
  - stable
notifications:
  email:
    recipients:
      - wordman05@gmail.com
branches:
  only:
    - master
script:
    - echo "TODO set up testing."
deploy:
  provider: heroku
  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
  app: steamwatch
  skip_cleanup: false
