language: node_js
node_js:
  - stable
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key: "0"
  app: 0
  skip_cleanup: false
